# Generated by Django 5.0.2 on 2024-02-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="slug",
        ),
    ]
